export enum ViewId {
    NONE = 'NONE',
    TRANSLATION_KEY = 'TRANSLATION_KEY',
    THREE_MUSEUM = 'THREE_MUSEUM',
    THREE_MAIN = 'THREE_MAIN',
    MAIN_REACT = 'MAIN_REACT',
    PROJECT_REACT = 'PROJECT_REACT',
    ENTRY_REACT = 'ENTRY_REACT',
}
