export enum ViewId {
    NONE = 'NONE',
    TRANSLATION_KEY = 'TRANSLATION_KEY',
    THREE_MUSEUM = 'THREE_MUSEUM',
    THREE_MAIN = 'THREE_MAIN',
    THREE_CINEMA = 'THREE_CINEMA',
    MAIN_REACT = 'MAIN_REACT',
    PROJECT_REACT = 'PROJECT_REACT',
    ENTRY_REACT = 'ENTRY_REACT',
    ABOUT_REACT = 'ABOUT_REACT',
    TEST_REACT = 'TEST_REACT',
    TEST_THREE = 'TEST_THREE',
}
