export enum AssetId {
    NONE = 'NONE',


    // 3D models
    GLTF_MAIN = 'GLTF_MAIN',
    GLTF_COMMON = 'GLTF_COMMON',
    GLTF_CINEMA = 'GLTF_CINEMA',


    IMAGE_ONE = 'IMAGE_ONE',
    IMAGE_TWO = 'IMAGE_TWO',
    IMAGE_THREE = 'IMAGE_THREE',
    IMAGE_FOUR = 'IMAGE_FOUR',
    IMAGE_FIVE = 'IMAGE_FIVE',
    IMAGE_SIX = 'IMAGE_SIX',
    IMAGE_SEVEN = 'IMAGE_SEVEN',
    IMAGE_EIGHT = 'IMAGE_EIGHT',
    IMAGE_NINE = 'IMAGE_NINE',
    TEXTURE_BAKE_MOUNTAIN = 'TEXTURE_BAKE_MOUNTAIN',
    IMAGE_DUDV = 'IMAGE_DUDV',
    HDR_STUDIO = 'HDR_STUDIO',
    TEXT_BLUR = 'TEXT_BLUR',
}